version: "3.9"

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: event-mariadb
    restart: unless-stopped
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      TZ: "Europe/Bucharest"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci"
      ]
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: ..
      dockerfile: src/main/java/Dockerfile
    container_name: event-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://event-mariadb:3306/${MARIADB_DATABASE}"
      SPRING_DATASOURCE_USERNAME: "${MARIADB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MARIADB_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "update"
      SPRING_PROFILES_ACTIVE: "dev"
    depends_on:
      - mariadb

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: clientsdb

  client-service:
    build:
      context: ../client-service
      dockerfile: ../client-service/Dockerfile
    container_name: client-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/clientsdb
      - CLIENT_EVENT_SERVICE_BASE_URL=http://backend:8080/api/event-manager
    depends_on:
      - mongodb
      - backend

volumes:
  mariadb_data:
